### ISSUE TITLE
There is no device can be used to do the computation

### ISSUE THREAD

**Issue by Dekken** [ROCmSoftwarePlatform/hiptensorflow#63]
Docker Tensorflow ROCm mistatch

@sunway513 is going to release 1.7 to dockerhub?

**Comment by Frenchie-Juice** [comment]
Having the same error message after going through all the procedure to install hiptensorflow on Ubuntu 16.04 on a MacBook Pro.
There is a Radeon GPU in there, so why is it not recognized by the ROCm stack ??

**Comment by Dekken** [comment]
It's a mismatch I believe between host rocm and docker version expected

docker version is 1.6.x

**Comment by Mandrewoid** [comment]
@Frenchie-Juice  Specifically what radeon gpu, and what intel CPU?

**Comment by gstoner** [comment]
We are upgrading to 1.7.1 right now we role out dates out with this release.   We also working on Rolling out Tensorflow 1.3 with this release,  right now we running 24 hours test on Tensorflow 1.3 against newly made available servers.  22 new nodes for testing.

**Comment by Frenchie-Juice** [comment]
Hi,




I figured out my problem.


It wasn't my Radeon card that was the issue, but my virtualization environment that used a generic GPU driver.


So basically TensorFlow wasn't detecting any GPU due to that problem.




At that stage, after everything I tried, I see only 2 options for me to get TensorFlow to work on the latest MacBook Pro:




1) wait for AMD to eventually release their ROCm stack to MacOS. Hopefully sometime this year.


2) install Ubuntu on the MacBook Pro, and install ROCm and HIPTensor.




Actually, there is even the 3rd option: AWS or an equivalent to run on the cloud.


 






Get Outlook for Android







On Fri, Feb 16, 2018 at 5:58 PM -0500, "Mandrewoid" <notifications@github.com> wrote:












@Frenchie-Juice  Specifically what radeon gpu, and what intel CPU?

**Comment by Mandrewoid** [comment]
@gstoner Is this 1.3 build going to come with a python 3 version?

**Comment by JorgeCeja** [comment]
@gstoner Do you have an ETA for the update(s)? Much appreciated!

**Comment by alecuba16** [comment]
@gstoner Will you release a source code version of the required binaries in order to compile for other distros like gentoo?

**Comment by Dekken** [comment]
I'm pretty sure this 99% the case - I have built most things manually - the DKMS might be a bit of a concern on different kernels I imagine

**Comment by alecuba16** [comment]
@Dekken I personally use Gentoo so I don't know what patches are needed, since many instructions are just for debian/ubuntu.

Do you have any checklist or order starting from nothing to finally the tensorflow python module of what I have to do?

**Comment by Dekken** [comment]
I have an out of date set of instructions if you'd like [a reference](https://github.com/lxcy/2.0.5-x86_64-debian8.6_hcc/blob/master/setup/rocm_master_rel.sh)

+ this and possibly some more

https://github.com/ROCmSoftwarePlatform/hiptensorflow/issues/65

**Comment by gstoner** [comment]
We have have been building  1.7.1 Beta 4 against Generic 4.13 kernel

**Comment by alecuba16** [comment]
@gstoner Where I can find the sources? hip-develop seems to be not working for me (1.7).

**Comment by gstoner** [comment]
Here is break down of the repos
Everything that sit on on top of the language runtimes https://github.com/ROCmSoftwarePlatform
The Development tool are here https://github.com/ROCm-Developer-Tools OpenCL is the exception it still in next Rep bellow
Main Body of the driver and System Software is here https://github.com/RadeonOpenCompute

HIP is in Developer-Tools Repo.

Greg

**Comment by Dekken** [comment]
@alecuba16

I've gone through [my script](https://github.com/Dekken/scripts/blob/master/hcc.sh) and updated it - PRs are welcome!

**Comment by whchung** [comment]
Please kindly try https://github.com/ROCmSoftwarePlatform/tensorflow/ and open the issue there in case it persists. This project has been deprecated and I'll close this repository very soon. Thanks for your understanding.
