### ISSUE TITLE
hiptensorflow Python 3 Support

### ISSUE THREAD

**Issue by pdiffley** [ROCmSoftwarePlatform/hiptensorflow#71]
I am installing hiptf in a python 3 virtual environment. When I run:

`pip install tensorflow-1.0.1-cp27-cp27mu-linux_x86_64.whl && rm tensorflow-1.0.1-cp27-cp27mu-linux_x86_64.whl
`

I receive the error:

`tensorflow-1.0.1-cp27-cp27mu-linux_x86_64.whl is not a supported wheel on this platform.`

I am under the impression this is because the installation guide installs the python 2.7 version of tensorflow. Is there a python 3 version of hiptf available or a way to work around this issue?

I am able to install hiptf in a python2.7 virtual environment and run the sample models with no issues.

**Comment by Mandrewoid** [comment]
I'm also interested in this. I'm not an expert on TF or HIP but I think it might be possible if building from source, to reconfigure bazel to build the python 3 version. in #63  it was mentioned a new version is coming soon... So I haven't taken the time to work on this.
My definition of soon might be different than others though, because that was 12 days ago.

**Comment by whchung** [comment]
Please kindly try https://github.com/ROCmSoftwarePlatform/tensorflow/ and open the issue there in case it persists. This project has been deprecated and I'll close this repository very soon. Thanks for your understanding.
